apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
  labels:
    app.kubernetes.io/part-of: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http  # Dynamically points to containerPort 8080 via the named flag
      protocol: TCP
  selector:
    app: frontend
